books = ["1-nephi", "2-nephi", "jacob", "enos", "jarom", "omni", "words-of-mormon", "mosiah", "alma", "helaman", "3-nephi", "4-nephi", "mormon", "ether", "moroni"]
chapters = {
    "1-nephi": 22, "2-nephi": 33, "jacob": 7, "enos": 1, "jarom": 1, "omni": 1, "words-of-mormon": 1,
    "mosiah": 29, "alma": 63, "helaman": 16, "3-nephi": 30, "4-nephi": 1,
    "mormon": 9, "ether": 15, "moroni": 10
}
languagesData= {
    "english": {
        "book-of-mormon": "The Book of Mormon",
        "another-testament-of-jesus-christ": "Another Testament of Jesus Christ",
        "english": "english",
        "french": "french",
        "spanish": "spanish",
        "german": "german",
        "1-nephi": "1 Nephi",
        "2-nephi": "2 Nephi",
        "jacob": "Jacob",
        "enos": "Enos",
        "jarom": "Jarom",
        "omni": "Omni",
        "words-of-mormon": "Words of Mormon",
        "mosiah": "Mosiah",
        "alma": "Alma",
        "helaman": "Helaman",
        "3-nephi": "3 Nephi",
        "4-nephi": "4 Nephi",
        "mormon": "Mormon",
        "ether": "Ether",
        "moroni": "Moroni",
        "chapter": "Chapter",
        "side-by-side-version": "Side by Side Version"
    },
    "spanish": {
        "book-of-mormon": "El Libro de Mormón",
        "another-testament-of-jesus-christ": "Otro Testamento de Jesucristo",
        "english": "ingles",
        "french": "frances",
        "spanish": "español",
        "german": "aleman",
        "1-nephi": "1 Nefi",
        "2-nephi": "2 Nefi",
        "jacob": "Jacob",
        "enos": "Enós",
        "jarom": "Jarom",
        "omni": "Omni",
        "words-of-mormon": "Palabras de Mormón",
        "mosiah": "Mosíah",
        "alma": "Alma",
        "helaman": "Helamán",
        "3-nephi": "3 Nefi",
        "4-nephi": "4 Nefi",
        "mormon": "Mormón",
        "ether": "Éter",
        "moroni": "Moroni",
        "chapter": "Capítulo",
        "side-by-side-version": "Versión Lado a Lado"
    },
    "french": {
        "book-of-mormon": "Le Livre de Mormon",
        "another-testament-of-jesus-christ": "Un Autre Témoignage de Jésus-Christ",
        "english": "anglais",
        "french": "français",
        "spanish": "espagnol",
        "german": "allemand",
        "1-nephi": "1 Néphi",
        "2-nephi": "2 Néphi",
        "jacob": "Jacob",
        "enos": "Énos",
        "jarom": "Jarom",
        "omni": "Omni",
        "words-of-mormon": "Paroles de Mormon",
        "mosiah": "Mosiah",
        "alma": "Alma",
        "helaman": "Hélaman",
        "3-nephi": "3 Néphi",
        "4-nephi": "4 Néphi",
        "mormon": "Mormon",
        "ether": "Éther",
        "moroni": "Moroni",
        "chapter": "Chapitre",
        "side-by-side-version": "Version Côte à Côte"
    },
    "german": {
        "book-of-mormon": "Das Buch Mormon",
        "another-testament-of-jesus-christ": "Ein weiteres Zeugnis von Jesus Christus",
        "english": "englisch",
        "french": "französisch",
        "spanish": "spanisch",
        "german": "deutsch",
        "1-nephi": "1 Nephi",
        "2-nephi": "2 Nephi",
        "jacob": "Jakob",
        "enos": "Enos",
        "jarom": "Jarom",
        "omni": "Omni",
        "words-of-mormon": "Worte von Mormon",
        "mosiah": "Mosiah",
        "alma": "Alma",
        "helaman": "Helaman",
        "3-nephi": "3 Nephi",
        "4-nephi": "4 Nephi",
        "mormon": "Mormon",
        "ether": "Ether",
        "moroni": "Moroni",
        "chapter": "Kapitel",
        "side-by-side-version": "Nebeneinander Version"
    }
}
